name: CI
on:
  workflow_dispatch:
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build the app
        run: ./gradlew assembleRelease

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          release_name: ${{ env.RNAME }} (${{ env.AARCH }})
          tag_name: ${{ env.TNAME }}${{ env.AARCH }}
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

    env:
      RNAME: Doggie
      ANAME: Doggie.
      TNAME: Git_compiled
      AARCH: arm
