name: CI
on:
  workflow_dispatch:
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build the app
        run: ./gradlew assembleRelease

      - name: release
        uses: actions/create-release@v1
        with:
          release_name: ${{ env.RNAME }}
          tag_name: ${{ env.TNAME }}
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

      - name: upload apk
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.RNAME }}_alpha
          path: ${{ env.apk_path }}
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}


    env:
      RNAME: Doggie
      TNAME: action_build
      apk_path: app/build/outputs/apk/release
